'use client';
import {useRef,useState} from 'react';
import {ArrowUpRight,CheckCircle2} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Textarea} from '@/components/ui/textarea';
import {NativeSelect} from '@/components/ui/native-select';
import {Button} from '@/components/ui/button';
import {quoteSchema} from '@/lib/quote';
import {getLeadSource} from '@/lib/lead-source';
import {track} from './site-client';
export function QuoteForm(){const[method,setMethod]=useState('phone');const[busy,setBusy]=useState(false);const[success,setSuccess]=useState(false);const[message,setMessage]=useState('');const[errors,setErrors]=useState<Record<string,string[]>>({});const started=useRef(0);const id=useRef('');const locked=useRef(false);const status=useRef<HTMLDivElement>(null);function begin(){if(!started.current){started.current=Date.now();id.current=crypto.randomUUID();track('form_start');}}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(locked.current)return;begin();setMessage('');const form=e.currentTarget;const data={...Object.fromEntries(new FormData(form)),started:started.current,requestId:id.current,source:getLeadSource()};const parsed=quoteSchema.safeParse(data);if(!parsed.success){const errs=parsed.error.flatten().fieldErrors;setErrors(errs);form.querySelector<HTMLElement>(`[name="${Object.keys(errs)[0]}"]`)?.focus();track('quote_submission_error',{reason:'validation'});return;}setErrors({});locked.current=true;setBusy(true);try{const r=await fetch('/api/quote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(parsed.data)});const result=await r.json() as {ok?:boolean;message?:string;errors?:Record<string,string[]>};if(r.ok&&result.ok){setSuccess(true);track('quote_submission_accepted');}else{setErrors(result.errors||{});track('quote_submission_error',{reason:String(r.status)});}setMessage(result.message||'Unable to send. Please call Apex.');}catch{setMessage('The connection was interrupted. Please try again or call (512) 825-1484. Your details are still here.');track('quote_submission_error',{reason:'network'});}finally{setBusy(false);locked.current=false;setTimeout(()=>status.current?.focus(),30);}}
 function error(n:string){return errors[n]?.length?<span className="field-error" id={n+'-error'}>{errors[n][0]}</span>:null;}function attrs(n:string){return {'aria-invalid':!!errors[n],'aria-describedby':errors[n]?n+'-error':undefined};}
 return <div className="quote-card">{success?<div className="success-state"><CheckCircle2 size={38}/><h3>Thank you for reaching out.</h3><div ref={status} tabIndex={-1} role="status">{message}</div><a className="text-link" href="tel:+15128251484">Call Apex with a question</a></div>:<form onSubmit={submit} onFocus={begin} noValidate><p className="eyebrow">A good place to start</p><h3>Get your free quote.</h3><p className="form-subtitle">A few details now. A clearer view ahead.</p><div className="form-fields"><div className="full"><Label htmlFor="name">Your name</Label><Input id="name" name="name" autoComplete="name" placeholder="Full name" required maxLength={100} {...attrs('name')}/>{error('name')}</div><div><Label htmlFor="method">How should we reach you?</Label><NativeSelect id="method" name="method" value={method} onChange={e=>setMethod(e.target.value)}><option value="phone">Phone call</option><option value="email">Email</option></NativeSelect></div><div><Label htmlFor="contact">{method==='phone'?'Phone number':'Email address'}</Label><Input key={method} id="contact" name="contact" type={method==='phone'?'tel':'email'} autoComplete={method==='phone'?'tel':'email'} placeholder={method==='phone'?'(512) 555-0123':'you@example.com'} required {...attrs('contact')}/>{error('contact')}</div><div><Label htmlFor="city">Service city or ZIP code</Label><Input id="city" name="city" placeholder="e.g. Spicewood" autoComplete="address-level2" required maxLength={100} {...attrs('city')}/>{error('city')}</div><div><Label htmlFor="service">What can we help with?</Label><NativeSelect id="service" name="service" defaultValue="Window cleaning"><option>Window cleaning</option><option>Pressure washing</option><option>Solar panel cleaning</option><option>Multiple services</option></NativeSelect></div><div className="full"><Label htmlFor="details">Anything else? <span>(optional)</span></Label><Textarea id="details" name="details" rows={3} maxLength={2000} placeholder="Interior or exterior? Any access concerns?" {...attrs('details')}/>{error('details')}</div><div className="honey" aria-hidden="true"><label htmlFor="website">Website</label><input id="website" name="website" tabIndex={-1} autoComplete="off"/></div></div>{message&&<div className="form-message" ref={status} role="alert" tabIndex={-1}>{message}</div>}<Button type="submit" disabled={busy} className="btn submit">{busy?'Sending request…':'Request a Quote'}<ArrowUpRight size={18}/></Button><p className="privacy-note">By submitting, you ask Apex to contact you about this inquiry. See our <a href="/privacy">privacy information</a>.</p><p className="form-fallback">Prefer to call? <a href="tel:+15128251484">(512) 825-1484</a></p></form>}</div>}
