import {services} from '@/lib/site';
const content:Record<string,{heading:string;body:string}[]>={
 'window-cleaning':[
 {heading:'Interior and exterior window cleaning',body:'Choose the sides of the glass you want cleaned, including patio doors and larger architectural panes. Tell us about upper floors, furniture near interior windows, and any areas that are difficult to reach. Your estimate defines the agreed work.'},
 {heading:'What affects your window-cleaning estimate?',body:'Pane count and size, glass condition, access, and interior or exterior scope affect the quote. Mention screens, tracks, sprinkler spotting, and construction residue separately so Apex can assess the work and explain any additional cost.'},
 {heading:'Planning window washing around your home',body:'Share your city or ZIP code and the type of windows you have. Before the visit, agree on gate access, pets, and furniture that needs moving. If you want patio or driveway cleaning too, include it in the same inquiry so the sequence can be discussed.'}],
 'pressure-washing':[
 {heading:'Driveway and walkway cleaning',body:'Driveways and walkways need an approach suited to their surface and condition. Include approximate size, material, slope, existing damage, and visible stains in your request. Persistent oil, rust, and other marks need assessment; complete stain removal is not assumed.'},
 {heading:'Patio cleaning and outdoor living spaces',body:'Tell Apex whether your patio is concrete, pavers, stone, or another material. Mention furniture, nearby planting, loose joints, coatings, and drainage. The estimate should explain the areas included and any preparation needed before cleaning.'},
 {heading:'Pressure washing or power washing?',body:'People often use both terms when looking for exterior cleaning. The appropriate method depends on the surface and buildup. Ask Apex which method is proposed for your property, including whether heat or a lower-pressure approach is appropriate; equipment and treatment are confirmed with the quote.'},
 {heading:'What affects the price?',body:'Surface area, material, condition, access, and the type of buildup affect the estimate. Send the service city and a description of the driveway, patio, or paths you want cleaned. Window cleaning can be requested alongside exterior surface care.'}],
 'solar-panel-cleaning':[
 {heading:'Plan around your installation',body:'Share the panel count if known, roof material, roof height, and manufacturer care guidance. Access and installation requirements shape the assessment. Ground-level photos or installation documents can help describe the system.'},
 {heading:'Cleaning scope and system performance',body:'Discuss visible surface buildup and cleaning needs separately from electrical faults or repairs. Cleaning does not guarantee a particular increase in output. Ask your installer about unexplained performance changes or suspected damage.'}]
};
export function ServiceDetails({slug}:{slug:string}){return <section className="wrap page-content"><div className="prose">{content[slug]?.map(item=><section key={item.heading}><h2>{item.heading}</h2><p>{item.body}</p></section>)}<h2>Serving Austin from Spicewood</h2><p>Apex is a service-area business serving homes around Austin and Lake Travis. Share your city or ZIP code to confirm coverage and scheduling.</p><div className="related-links"><a href="/service-areas/austin">Austin service information</a><a href="/service-areas/lakeway">Lakeway</a><a href="/service-areas/bee-cave">Bee Cave</a><a href="/service-areas/spicewood">Spicewood</a></div><div className="related-links"><a href="/gallery">View the Apex gallery</a><a href="/reviews">Read customer reviews</a><a href="/contact">Request a free quote</a></div><h2>More exterior care</h2><div className="related-links">{services.filter(s=>s.slug!==slug).map(s=><a key={s.slug} href={'/services/'+s.slug}>{s.name}</a>)}</div></div></section>}
