import photoAssets from '@/lib/photo-assets.json';
import {ArrowUpRight, ArrowRight, MapPin, Check, Phone} from 'lucide-react';
import {services,origin,businessHours} from '@/lib/site';
import {FAQs} from './site-client';
import {QuoteForm} from './quote-form';
export function Photo({name,alt,className='',priority=false}:{name:string;alt:string;className?:string;priority?:boolean}){
 const asset=(photoAssets as Record<string,{file:string;width:number;height:number}>)[name];
 const file=asset?.file||name;
 const sizes=(name==='hero-gallery-1'||name==='apex-work-truck-0094')?'(max-width: 760px) 100vw, 51vw':'(max-width: 760px) calc(100vw - 48px), (max-width: 1100px) 50vw, 45vw';
 const widths=asset||name==='hero-gallery-1'?[640,960,1280]:[640,1280];
 return <picture className={className}><source type="image/avif" srcSet={widths.map(w=>`/images/${file}-${w}.avif ${w}w`).join(', ')} sizes={sizes}/><img src={`/images/${file}-1280.webp`} srcSet={widths.map(w=>`/images/${file}-${w}.webp ${w}w`).join(', ')} sizes={sizes} alt={alt} width={asset?.width||1280} height={asset?.height||960} loading={priority?'eager':'lazy'} fetchPriority={priority?'high':'auto'}/></picture>
}
export function CTA({placement='section'}:{placement?:string}){return <a className="btn" data-quote={placement} href="/contact">Get a Free Quote <ArrowUpRight size={18}/></a>}
export function Services(){return <section className="section wrap" id="services"><div className="section-heading"><div><p className="eyebrow">A little care. A visible difference.</p><h2>Bring out the best<br/>in your home.</h2></div><p>Clearer windows. Fresher outdoor spaces.<br/>Thoughtful care, starting with a conversation.</p></div><div className="services-grid">{services.map((s,i)=><a href={'/services/'+s.slug} className="service" key={s.slug}><div className="service-image"><Photo name={s.image} alt={s.alt}/><span className="image-arrow"><ArrowUpRight size={22}/></span></div><p className="eyebrow">0{i+1} / {i===0?'Our specialty':'Exterior care'}</p><h3>{s.name}</h3><p>{s.description}</p><span className="text-link">Explore service <ArrowRight size={16}/></span></a>)}</div></section>}
export function Work(){return <section className="work-section section"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">A closer look</p><h2>Good glass. Great views.</h2></div><a href="/gallery" className="text-link">Explore the gallery <ArrowUpRight size={18}/></a></div><div className="work-grid"><figure><Photo name="gallery-1" alt="Wraparound glass beneath a modern home's deep roof overhang"/><figcaption><span>Architectural glass</span></figcaption></figure><figure><Photo name="gallery-4" alt="Glass doors opening from a covered patio into a home"/><figcaption><span>Indoor meets outdoor</span></figcaption></figure></div></div></section>}
export function Process(){return <section className="section wrap process"><div><p className="eyebrow">Simple from the start</p><h2>A clearer view.<br/>Without the hassle.</h2></div><ol>{[['Tell us about your home','Choose a service and share your city. A few details are all it takes to get started.'],['Agree on the details','Discuss access, scope, and pricing with Apex, then confirm a time that works.'],['Enjoy the difference','Make room for more natural light and a fresh perspective on your home.']].map(([h,p],i)=><li key={h}><span>0{i+1}</span><div><h3>{h}</h3><p>{p}</p></div></li>)}</ol></section>}
export function Owner(){return <section className="owner wrap"><Photo name="brett-with-dog" alt="Brett standing with a dog beside a work truck"/><div className="owner-copy"><p className="eyebrow">Your local connection</p><h2>A local business.<br/>A familiar face.</h2><p>Meet Brett, the owner behind Apex Window Cleaning. With 8 years in business, Apex is based in Spicewood and serves homes around Lake Travis and Austin.</p><p>Have a question about your windows, your property, or where to start? Reach out and talk through what your home needs.</p><a className="text-link" href="/contact">Get in touch with Apex <ArrowUpRight size={18}/></a><div className="signature">Brett <span>Owner, Apex Window Cleaning</span></div></div></section>}
export function FAQSection(){return <section className="section wrap faq-section"><div><p className="eyebrow">Before we stop by</p><h2>A few things<br/>you might be wondering.</h2><p>More questions? We’re a phone call away.</p><a className="text-link" href="tel:+15128251484"><Phone size={16}/>(512) 825-1484</a></div><FAQs/></section>}
export function QuoteSection(){return <section className="quote-section" id="quote"><div className="wrap quote-grid"><div className="quote-intro"><p className="eyebrow">Let’s brighten your day</p><h2>Your view.<br/>Only clearer.</h2><p>Free same-day quotes are available. Tell us a little about your home, and we’ll use your preferred contact method to discuss the work and your estimate.</p><div className="coverage"><MapPin size={20}/><div><strong>Spicewood roots. Lake Travis reach.</strong><p>Serving Spicewood, Lakeway, Bee Cave, Austin, and surrounding communities.</p><a href="/service-areas">Explore our service areas <ArrowRight size={15}/></a></div></div><a className="quote-phone" href="tel:+15128251484">(512) 825-1484</a><p className="small-copy">{businessHours.display}</p></div><QuoteForm/></div></section>}
export function Footer(){return <footer><div className="wrap footer-grid"><div><a className="footer-brand" href="/"><img src="/images/apex-logo-260.webp" width="140" height="105" alt="Apex Window Cleaning"/></a><p>A clearer view of home.<br/>Spicewood · Lake Travis · Austin</p></div><div><h3>Explore</h3><a href="/about">About Apex</a><a href="/gallery">Our Work</a><a href="/reviews">Reviews</a><a href="/blog">Home Care Journal</a><a href="/specials">Specials</a></div><div><h3>Our services</h3>{services.map(s=><a href={'/services/'+s.slug} key={s.slug}>{s.name}</a>)}<a href="/service-areas">Service Areas</a></div><div><h3>Let’s talk</h3><p>{businessHours.display}</p><a href="tel:+15128251484">(512) 825-1484</a><a href="mailto:apexwood01@gmail.com">apexwood01@gmail.com</a><a className="text-link" data-quote="footer" href="/contact">Get a Free Quote <ArrowUpRight size={16}/></a></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} Apex Window Cleaning</span><a href="/privacy">Privacy</a></div></footer>}
export function Schema({data}:{data:object}){return <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(data).replace(/</g,'\\u003c')}}/>}
export function Breadcrumbs({items}:{items:{name:string;path:string}[]}){return <><nav className="breadcrumbs wrap" aria-label="Breadcrumb"><a href="/">Home</a>{items.map(x=><span key={x.path}> / <a href={x.path}>{x.name}</a></span>)}</nav><Schema data={{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{name:'Home',path:'/'},...items].map((x,i)=>({'@type':'ListItem',position:i+1,name:x.name,item:origin+x.path}))}}/></>}
