'use client';
import {useEffect,useState} from 'react';
import {Menu, X, Phone, ArrowUpRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
import {faqs} from '@/lib/site';
export function track(event:string,extra:Record<string,string>={}) {window.dispatchEvent(new CustomEvent('apex:analytics',{detail:{event,page:window.location.pathname,...extra}}));}
export function Tracking(){useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;const lifecycle=new AbortController();if(context&&document.getElementById('quote')){try{void Promise.resolve(context.registerTool({name:'start_quote_request',title:'Open the quote form',description:'Bring the visible quote form into view. Does not submit an inquiry.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object.');document.getElementById('quote')?.scrollIntoView({behavior:'instant'});document.getElementById('name')?.focus();return {status:'form_open',submitted:false};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}}const click=(e:MouseEvent)=>{const a=(e.target as Element).closest('a');if(a?.getAttribute('href')?.startsWith('tel:'))track('phone_click');else if(a?.dataset.quote)track('quote_cta_click',{placement:a.dataset.quote});};document.addEventListener('click',click);return()=>{document.removeEventListener('click',click);lifecycle.abort();};},[]);return null;}
export function Header(){const[open,setOpen]=useState(false);useEffect(()=>{const fn=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);document.getElementById('menu-toggle')?.focus();}};document.addEventListener('keydown',fn);return()=>document.removeEventListener('keydown',fn);},[]);return <><header className="header"><a href="/" className="brand" aria-label="Apex Window Cleaning home"><img src="/images/apex-window-cleaning-logo.png" alt="Apex Window Cleaning" width="130" height="100"/></a><nav className="desktop-nav" aria-label="Main navigation"><a href="/services">Services</a><a href="/gallery">Our Work</a><a href="/about">About</a><a href="/service-areas">Service Areas</a></nav><div className="header-actions"><a className="header-phone" href="tel:+15128251484"><Phone size={15}/>(512) 825-1484</a><a className="btn small" data-quote="header" href="/contact">Get a Free Quote <ArrowUpRight size={16}/></a><Button id="menu-toggle" className="menu-toggle" variant="ghost" aria-expanded={open} aria-controls="mobile-menu" aria-label={open?'Close menu':'Open menu'} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button></div>{open&&<nav id="mobile-menu" aria-label="Mobile navigation">{[['Services','/services'],['Our Work','/gallery'],['About','/about'],['Service Areas','/service-areas'],['Get a Free Quote','/contact']].map(([n,l])=><a key={l} href={l} onClick={()=>setOpen(false)}>{n}</a>)}</nav>}</header><div className="mobile-bar"><a href="tel:+15128251484"><Phone size={17}/> Call Apex</a><a data-quote="mobile-bar" href="/contact">Get a Quote <ArrowUpRight size={17}/></a></div></>}
export function FAQs(){return <Accordion type="single" collapsible className="faq-list">{faqs.map(([q,a],i)=><AccordionItem value={String(i)} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion>}
