export const origin = 'https://www.apexwindowcleaningatx.com';
export const business = { name:'Apex Window Cleaning', phone:'(512) 825-1484', email:'apexwood01@gmail.com' };
export const services = [
 {slug:'window-cleaning',name:'Window cleaning',tag:'A brighter outlook',description:'Let the light in. Interior and exterior window cleaning for a clearer view of the home you love.',image:'gallery-3',alt:'Tall architectural windows reflecting a patio',details:'Choose exterior glass, interior glass, or both. Tell us about window height, access, and any visible spotting so your estimate reflects the work you need.',scope:['Interior and exterior glass quoted to your needs','Screens, tracks, and hard-water treatment discussed separately','High or difficult-to-reach windows assessed before scheduling']},
 {slug:'pressure-washing',name:'Pressure washing',tag:'Fresh from the outside in',description:'Pressure washing for driveways, patios, and walkways in Austin, Lake Travis, and Spicewood. Request a quote for your outdoor surfaces.',image:'patio-after',alt:'Stone patio beside a landscaped garden',details:'Looking for power washing in Austin? Tell us which driveways, patios, or walkways need attention. Surface material, condition, size, and access determine the cleaning approach and estimate. Mention delicate stone, existing damage, and stubborn marks so Apex can assess what is suitable before work begins.',scope:['Driveways, patios, and walkways','Surface suitability reviewed before work is agreed','Delicate stone, siding, and painted surfaces need individual assessment']},
 {slug:'solar-panel-cleaning',name:'Solar panel cleaning',tag:'Care for your investment',description:'Clear away surface buildup with cleaning planned around your panels and access.',image:'gallery-5',alt:'Residential rooftop solar panel array',details:'Share your panel count if you know it, roof type, and any access concerns. Cleaning requirements vary by installation and manufacturer.',scope:['Residential panel cleaning by agreed scope','Roof height, pitch, and access reviewed first','No guaranteed energy increase or electrical repairs']},
];
export const faqs = [
 ['How quickly can I get a quote?','Free same-day quotes are available. Share your city, the service you need, and a few details about your property, or call (512) 825-1484 to discuss your estimate.'],
 ['What goes into my quote?','The amount of glass, interior or exterior scope, condition, and access all matter. Your city and a short description are enough to start the conversation. Photos may help clarify the scope later.'],
 ['Can I choose interior or exterior cleaning?','Yes—request interior glass, exterior glass, or both. The estimate should identify the areas to be cleaned before you agree to the work.'],
 ['Are screens, tracks, and hard-water spots included?','Do not assume these are included in a glass-cleaning quote. Mention them in your request so Apex can confirm the treatment, suitability, and any additional cost.'],
 ['How should I prepare my home?','Ask about access before your visit. Let Apex know about locked gates, pets, delicate items near windows, and anything that needs special care. Confirm what should be moved when scheduling.'],
 ['What about high windows or difficult access?','Mention upper floors, steep ground, roof access, and large panes in your request. Apex will need to review access before confirming the job.'],
 ['What happens if the weather changes?','Weather can affect outdoor work. Contact Apex to discuss the conditions and confirm your appointment; scheduling changes are handled directly.'],
 ['How often should my windows be cleaned?','That depends on your surroundings, pollen, sprinkler exposure, and how quickly buildup returns. Tell Apex what you notice between cleanings to discuss a suitable frequency.'],
];
